import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));
const stylesDir = path.join(root, 'src', 'styles');

/*
 * A stylesheet is not a set of files; it is a cascade. A later module may only
 * refine what an earlier one established, so this order *is* the sheet's
 * meaning and it is written out rather than globbed — a directory listing has
 * no intent, and a filename that sorts differently on another platform would
 * silently change which rule wins.
 *
 * The numeric prefixes exist so the order is legible in the directory too, but
 * this array remains the authority: `assertDeclared` fails the build if a file
 * appears in src/styles without appearing here, so a new module can never be
 * appended to the cascade by accident.
 */
export const STYLESHEET_MODULES = [
  '00-tokens.css',
  '01-controls.css',
  '02-home.css',
  '03-rows-and-workspace.css',
  '04-library.css',
  '05-atlas.css',
  '06-disclosure.css',
  '07-facts.css',
  '08-buttons.css',
  '09-navigator.css',
  '10-responsive.css',
  '11-garden.css',
  '12-home-convergence.css',
  '13-search.css',
  '14-thematic-nav.css',
  '15-projects.css',
  '16-spacing.css',
  '17-triage.css',
  '18-library-facets.css',
  '19-garden-review.css',
  '20-shell.css',
  '21-shell-tabs.css',
  '22-daily-loop.css',
  '23-unit-surface.css',
  '24-projects-workstreams.css',
  '25-palettes.css',
];

/*
 * plugin/styles.css used to be the file people edited. It is an artifact now,
 * and an artifact that does not say so invites an edit the next build throws
 * away without telling anyone.
 */
export const GENERATED_BANNER =
  '/* GENERATED by build-styles.mjs from src/styles/ — do not edit this file.\n'
  + ' * Edit the module in src/styles/ that owns the rule, then run `npm run build`. */\n';

export function stylesheetSources() {
  return STYLESHEET_MODULES.map((name) => ({
    relative: path.posix.join('src/styles', name),
    source: fs.readFileSync(path.join(stylesDir, name), 'utf8'),
  }));
}

function assertDeclared() {
  const present = fs.readdirSync(stylesDir).filter((name) => name.endsWith('.css'));
  const undeclared = present.filter((name) => !STYLESHEET_MODULES.includes(name));
  if (undeclared.length) {
    throw new Error(
      `src/styles contains modules the cascade does not declare: ${undeclared.sort().join(', ')}. `
      + 'Add them to STYLESHEET_MODULES in build-styles.mjs, in the position the cascade needs.',
    );
  }
  const missing = STYLESHEET_MODULES.filter((name) => !present.includes(name));
  if (missing.length) {
    throw new Error(`build-styles.mjs declares modules that do not exist: ${missing.join(', ')}`);
  }
}

export function composeStylesheet() {
  assertDeclared();
  return GENERATED_BANNER + stylesheetSources().map(({ source }) => source).join('');
}

export function writeStylesheet(outfile = path.join(root, 'plugin', 'styles.css')) {
  const css = composeStylesheet();
  fs.mkdirSync(path.dirname(outfile), { recursive: true });
  fs.writeFileSync(outfile, css, 'utf8');
  return css;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const css = writeStylesheet();
  console.log(
    `styles: composed ${STYLESHEET_MODULES.length} modules -> plugin/styles.css `
    + `(${Buffer.byteLength(css)} bytes)`,
  );
}
